[movie_theater_y]
title = "다음영화 영화관 ─ 현재상영"
url = "https://movie.daum.net/premovie/theater?flag=Y"
entrySelector = "div.box_movie ol li"
titleSelector = "a[class='link_txt']"
linkSelector = "a.link_txt"
imageSelector = "img.img_thumb"
contentSelector = "div.thumb_cont > span.txt_info > span"
waitUntil = "networkidle"

[movie_theater_c]
title = "다음영화 영화관 ─ 개봉예정"
url = "https://movie.daum.net/premovie/theater?flag=C"
entrySelector = "div.box_movie ol li"
titleSelector = "a[class='link_txt']"
linkSelector = "a.link_txt"
imageSelector = "img.img_thumb"
contentSelector = "div.thumb_cont > span.txt_info > span"
waitUntil = "networkidle"

[movie_netflix_c]
title = "[다음영화] 넷플릭스 ─ 종료예정"
url = "https://movie.daum.net/premovie/netflix?flag=C"
entrySelector = "ul.list_movieranking.aniposter_ott li"
titleSelector = "a[class='link_txt']"
linkSelector = "a.link_txt"
imageSelector = "img.img_thumb"
contentSelector = "div.thumb_cont > span.txt_info > span"
waitUntil = "networkidle"

[movie_netflix_y]
title = "[다음영화] 넷플릭스 ─ 공개예정"
url = "https://movie.daum.net/premovie/netflix?flag=Y"
entrySelector = "ul.list_movieranking.aniposter_ott li"
titleSelector = "a[class='link_txt']"
linkSelector = "a.link_txt"
imageSelector = "img.img_thumb"
contentSelector = "div.thumb_cont > span.txt_info > span"
waitUntil = "networkidle"

[movie_watcha_c]
title = "[다음영화] 왓챠 ─ 종료예정"
url = "https://movie.daum.net/premovie/watcha?flag=C"
entrySelector = "ul.list_movieranking.aniposter_ott li"
titleSelector = "a[class='link_txt']"
linkSelector = "a.link_txt"
imageSelector = "img.img_thumb"
contentSelector = "div.thumb_cont > span.txt_info > span"
waitUntil = "networkidle"

[movie_watcha_y]
title = "[다음영화] 왓챠 ─ 공개예정"
url = "https://movie.daum.net/premovie/watcha?flag=Y"
entrySelector = "ul.list_movieranking.aniposter_ott li"
titleSelector = "a[class='link_txt']"
linkSelector = "a.link_txt"
imageSelector = "img.img_thumb"
contentSelector = "div.thumb_cont > span.txt_info > span"
waitUntil = "networkidle"

[movie_magazine]
title = "다음 영화 ─ 매거진"
url = "https://movie.daum.net/contents/1boon"
entrySelector = "ul.list_contents li"
titleSelector = "strong a.link_txt"
linkSelector = "a.link_txt"
contentSelector = "span.txt_info"
imageSelector = "span.bg_img"
waitUntil = "networkidle"

[movie_brunch]
title = "다음 영화 ─ 브런치"
url = "https://movie.daum.net/contents/brunch"
entrySelector = "ul.list_contents li"
titleSelector = "strong a.link_txt"
linkSelector = "a.link_txt"
contentSelector = "span.txt_info"
imageSelector = "span.bg_img"
waitUntil = "networkidle"
